
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KS4_ADDRESS }}
          username: ${{ secrets.KS4_USERNAME }}
          password: ${{ secrets.KS4_PASSWORD }}
          port: ${{ secrets.KS4_PORT }}
          script: |
            whoami
            echo $HOME  
            pwd
            ls -l 
      - run: 'sudo echo "$CRT" > /etc/ssl/private/wildcard-pknw1.co.uk.pem && sudo chmod 500 /etc/ssl/private/wildcard-pknw1.co.uk.pem'
        shell: bash
        env:
           CRT: ${{secrets.CRT_PKNW1}}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! && echo pk

      - name: Install HAProxy
        run: sudo apt-get install -y haproxy
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Launch HAProxy ${{ steps.show-version.outputs.version }}
        run: /usr/sbin/haproxy -c -f $GITHUB_WORKSPACE/test.cfg
