
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KS4_ADDRESS }}
          username: ${{ secrets.KS4_USERNAME }}
          password: ${{ secrets.KS4_PASSWORD }}
          port: ${{ secrets.KS4_PORT }}
          script: |
            pwd
	    hostname
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install HAProxy
        run: ls -l $GITHUB_WORKSPACE
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Launch HAProxy ${{ steps.show-version.outputs.version }}
        run: echo haproxy -c -f .github/test.cfg
